# yaml-language-server: $schema=https://trovu.net/schema/config.yml
#
# Documentation:
# https://trovu.net/docs/users/advanced/#custom-configuration

namespaces:
- o
- en
- .us
- github: .
  name: my
defaultKeyword: g
language: en
country: kz
